# Generated by Django 5.0.3 on 2024-03-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv_app', '0003_berita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Berita',
        ),
    ]
