# Generated by Django 5.0.3 on 2024-03-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv_app', '0005_berita'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
